N 8000
T 20000
duration 0.020
diffusivity_intra 2e-09
diffusivity_extra 2e-09
scheme_file /home/mhough/dev/sbi4dwi/validation/mcmr/mcds/straight_90_scheme.scheme
exp_prefix /home/mhough/dev/sbi4dwi/validation/mcmr/mcds/straight_90_intra
scale_from_stu 1
write_txt 1
write_bin 0
write_traj_file 0
num_process 12
ini_walkers_pos intra
<obstacle>
<axons_list>
/home/mhough/dev/sbi4dwi/validation/mcmr/mcds/straight_90_geometry.swc
permeability global 0.0
</axons_list>
</obstacle>
<voxel>
0 0 0
0.01 0.01 0.01
</voxel>
<END>
