"""
3-fibre forward model + acquisition shared by validation/validate_force_3fiber.py
and tests/validation/test_force_3fiber_integration.py.

Pure functions — no side effects beyond JAX dispatch. Extracted from the
validation script so the wiring is independently testable.
"""

from __future__ import annotations

from typing import Any

import jax
import jax.numpy as jnp
import numpy as np

from dmipy_jax.acquisition import JaxAcquisition
from dmipy_jax.pipeline.simulator import ModelSimulator


def make_multishell_acquisition() -> JaxAcquisition:
    """Reproducible 90-direction 2-shell acquisition (32@b=1k, 56@b=2k, 2@b=0).

    Same seed/layout as validate_force_replication_v2.make_multishell_acquisition
    so the two validation scripts share an identical gtab and the cached
    DIPY FORCE library generated by v2 is reusable here.
    """
    key = jax.random.PRNGKey(0)
    k1, k2 = jax.random.split(key)

    def rand_vecs(k, n):
        z = jax.random.normal(k, (n, 3))
        return z / jnp.linalg.norm(z, axis=-1, keepdims=True)

    v0 = jnp.array([[1.0, 0.0, 0.0]] * 2)
    v1 = rand_vecs(k1, 32)
    v2 = rand_vecs(k2, 56)
    bvals = jnp.concatenate(
        [jnp.zeros(2), jnp.full(32, 1e9), jnp.full(56, 2e9)]
    )
    bvecs = jnp.concatenate([v0, v1, v2], axis=0)
    return JaxAcquisition(bvalues=bvals, gradient_directions=bvecs)


def acq_to_gtab_si(acq: JaxAcquisition):
    """JaxAcquisition (SI b-values, s/m^2) -> dipy gradient_table (s/mm^2).

    Lazy import of dipy keeps this module light when only the forward model
    is needed.
    """
    from dipy.core.gradients import gradient_table

    bvals = np.asarray(acq.bvalues) / 1e6
    bvecs = np.asarray(acq.gradient_directions)
    return gradient_table(bvals, bvecs=bvecs)


def three_stick_signal(
    acq: JaxAcquisition,
    mu1: jnp.ndarray,
    mu2: jnp.ndarray,
    mu3: jnp.ndarray,
    f1: float,
    f2: float,
    f_iso: float = 0.05,
    d_par: float = 1.7e-9,
    d_iso: float = 3.0e-9,
) -> jnp.ndarray:
    """Three-stick + isotropic mixture signal under SI b-values.

    f3 = 1 - f1 - f2 - f_iso (implicit). At b=0 the four terms collapse to
    1.0 each so the weighted sum is exactly f1 + f2 + f3 + f_iso = 1.
    """
    f3 = 1.0 - f1 - f2 - f_iso
    cos1 = acq.gradient_directions @ mu1
    cos2 = acq.gradient_directions @ mu2
    cos3 = acq.gradient_directions @ mu3
    s1 = jnp.exp(-acq.bvalues * d_par * cos1 ** 2)
    s2 = jnp.exp(-acq.bvalues * d_par * cos2 ** 2)
    s3 = jnp.exp(-acq.bvalues * d_par * cos3 ** 2)
    s_iso = jnp.exp(-acq.bvalues * d_iso)
    return f1 * s1 + f2 * s2 + f3 * s3 + f_iso * s_iso


def build_three_stick_simulator(acq: JaxAcquisition) -> ModelSimulator:
    """7-param planar 3-stick simulator for dmipy-JAX library generation.

    params layout: ``[d_par, theta1, theta2, theta3, f1, f2, f_iso]``
    All three sticks are placed in the +x/+z plane at angles
    theta_i from the z axis: ``mu_i = [sin θ_i, 0, cos θ_i]``.
    """
    def forward_fn(params, acq):
        d_par = params[0]
        t1, t2, t3 = params[1], params[2], params[3]
        f1, f2, f_iso = params[4], params[5], params[6]
        f3 = 1.0 - f1 - f2 - f_iso
        mu1 = jnp.array([jnp.sin(t1), 0.0, jnp.cos(t1)])
        mu2 = jnp.array([jnp.sin(t2), 0.0, jnp.cos(t2)])
        mu3 = jnp.array([jnp.sin(t3), 0.0, jnp.cos(t3)])
        cos1 = acq.gradient_directions @ mu1
        cos2 = acq.gradient_directions @ mu2
        cos3 = acq.gradient_directions @ mu3
        s1 = jnp.exp(-acq.bvalues * d_par * cos1 ** 2)
        s2 = jnp.exp(-acq.bvalues * d_par * cos2 ** 2)
        s3 = jnp.exp(-acq.bvalues * d_par * cos3 ** 2)
        s_iso = jnp.exp(-acq.bvalues * 3.0e-9)
        return f1 * s1 + f2 * s2 + f3 * s3 + f_iso * s_iso

    return ModelSimulator(
        forward_fn=forward_fn,
        parameter_names=[
            "d_par", "theta1", "theta2", "theta3", "f1", "f2", "f_iso",
        ],
        parameter_ranges={
            "d_par": (1.0e-9, 2.5e-9),
            "theta1": (0.0, float(jnp.pi)),
            "theta2": (0.0, float(jnp.pi)),
            "theta3": (0.0, float(jnp.pi)),
            "f1": (0.1, 0.6),
            "f2": (0.1, 0.6),
            "f_iso": (0.0, 0.2),
        },
        acquisition=acq,
    )
