"""
PRISM's synthetic crossing-fibre benchmark (doc 007 §5 Phase A).

Protocol from arXiv:2604.00250 §3.1:
  - 3 shells b ∈ {1000, 2000, 3000} s/mm², 64 directions each + 1 b0 → N=193
  - 16 crossing angles 15°…90° in 5° steps + single-fibre controls
  - 200 voxels per condition → 3,400 voxels; Rician noise at SNR 30 (10, 50)
  - metric: best-match angular error, recall (detected if < 20°) — see
    ``prism_jax.angular_error_best_match``

Unspecified in the paper and fixed here: crossing fractions 0.5/0.5,
f_i = 0.5, no CSF/GM/restricted signal in the ground truth, fibre 1 along
+x, fibre 2 rotated in the x–y plane. Signals are generated by
``prism_jax.forward`` (in-model benchmark, as in the paper).

Voxels are laid out as a (17, 10, 20) volume, one 10×20 slice per
condition, so the spatial priors act on homogeneous neighbourhoods.
"""

from __future__ import annotations

import numpy as np
import jax.numpy as jnp

from dmipy_jax.validation.prism_jax import PrismConfig, forward

ANGLES = tuple(range(15, 91, 5))          # 16 conditions
SLICE = (10, 20)                          # 200 voxels each


def prism_scheme(n_dirs: int = 64, seed: int = 0):
    """(bvals_SI (193,), bvecs (193,3)); electrostatic-ish random dirs."""
    from dipy.core.sphere import disperse_charges, HemiSphere
    rng = np.random.default_rng(seed)
    theta = np.pi * rng.random(n_dirs)
    phi = 2 * np.pi * rng.random(n_dirs)
    hs, _ = disperse_charges(HemiSphere(theta=theta, phi=phi), 5000)
    d = hs.vertices
    bv = np.concatenate([[0.0], np.repeat([1000.0, 2000.0, 3000.0], n_dirs)])
    gv = np.concatenate([np.zeros((1, 3)), d, d, d])
    return bv * 1e6, gv


def _unit(v):
    v = np.asarray(v, float)
    return v / np.linalg.norm(v)


def make_benchmark(snr: float | None = 30.0, fintra: float = 0.5,
                   fracs: tuple[float, float] = (0.5, 0.5), seed: int = 0,
                   n_dirs: int = 64):
    """Returns dict(data (17,10,20,193), mask, bvals, bvecs, gt_dirs (N,2,3),
    angle_per_voxel (N,), cfg)."""
    bvals, bvecs = prism_scheme(n_dirs, seed)
    cfg = PrismConfig(n_fibres=2)
    n_cond = len(ANGLES) + 1
    shape = (n_cond,) + SLICE
    per = SLICE[0] * SLICE[1]
    N = n_cond * per
    n1 = _unit([1, 0, 0])
    gt = np.zeros((N, 2, 3))
    fr = np.zeros((N, 5))
    ang = np.zeros(N)
    for c in range(n_cond):
        sl = slice(c * per, (c + 1) * per)
        if c < len(ANGLES):
            a = np.radians(ANGLES[c])
            gt[sl, 0] = n1
            gt[sl, 1] = _unit([np.cos(a), np.sin(a), 0])
            fr[sl, 2], fr[sl, 3] = fracs
            ang[sl] = ANGLES[c]
        else:                                     # single-fibre controls
            gt[sl, 0] = n1
            fr[sl, 2] = 1.0
            ang[sl] = 0
    phys = {
        "s0": jnp.ones(N), "fracs": jnp.asarray(fr), "dirs": jnp.asarray(gt),
        "fintra": jnp.full(N, fintra), "d_par": jnp.asarray(cfg.d_par),
        "d_perp": jnp.asarray(cfg.d_perp), "sigma": None,
    }
    clean = np.asarray(forward(phys, jnp.asarray(bvals), jnp.asarray(bvecs), cfg))
    if snr is not None:
        rng = np.random.default_rng(seed + 1)
        s = 1.0 / snr
        clean = np.sqrt((clean + rng.normal(0, s, clean.shape)) ** 2
                        + rng.normal(0, s, clean.shape) ** 2)
    data = np.zeros(shape + (len(bvals),), np.float32)
    data[np.ones(shape, bool)] = clean
    return {"data": data, "mask": np.ones(shape, bool), "bvals": bvals,
            "bvecs": bvecs, "gt_dirs": gt, "angle": ang, "gt_fracs": fr,
            "fintra": fintra, "cfg": cfg}


def score_by_angle(pred_dirs, pred_fracs, bench, frac_min: float = 0.05):
    """Per-condition (angle → mean error, recall) plus overall, PRISM-style."""
    from dmipy_jax.validation.prism_jax import angular_error_best_match
    out = {}
    for a in list(ANGLES) + [0]:
        m = bench["angle"] == a
        gt = bench["gt_dirs"][m].copy()
        if a == 0:
            gt[:, 1] = 0.0                        # single fibre: no 2nd GT
        out[a] = angular_error_best_match(pred_dirs[m], pred_fracs[m], gt, frac_min)
    gt_all = bench["gt_dirs"].copy()
    gt_all[bench["angle"] == 0, 1] = 0.0
    out["overall"] = angular_error_best_match(pred_dirs, pred_fracs, gt_all, frac_min)
    return out


def msmt_peaks_on_benchmark(bench, sh_order_max: int = 8):
    """MSMT-CSD with oracle responses on the synthetic set → (dirs, fracs)
    in the same (N,5,3)/(N,5) layout for scoring."""
    from dipy.core.gradients import gradient_table
    from dipy.data import default_sphere
    from dmipy_jax.validation.msmt_baseline import msmt_csd_pam
    gtab = gradient_table(bench["bvals"] / 1e6, bvecs=bench["bvecs"])
    wm = np.zeros(bench["mask"].shape, bool)
    wm[bench["mask"]] = bench["angle"] == 0          # GT single-fibre voxels
    pam, _ = msmt_csd_pam(bench["data"], gtab, bench["mask"], default_sphere,
                          sh_order_max=sh_order_max, wm_mask=wm)
    m = bench["mask"]
    dirs = pam.peak_dirs[m]
    vals = pam.peak_values[m]
    vals = vals / np.maximum(vals.sum(1, keepdims=True), 1e-12)   # relative
    return dirs, vals
